/**
 * Combat V2 - Engine Module Exports
 *
 * Central export point for all combat engine functionality.
 */

// Damage calculation
export {
  calculateAndApplyDamage,
  applyWoundsToEntity,
  healEntity,
  createDamageInstance,
  getTotalWoundCount,
  hasWoundType,
  getHighestWoundCount,
  type FullDamageResult,
  type WoundApplicationResult,
  type HealingResult,
} from "./damage-calculator";

// Wound tracking
export {
  WOUND_DEFINITIONS,
  computeWoundPenalties,
  getEntityWithPenalties,
  applyBleedingDamage,
  addWounds,
  removeWounds,
  setWounds,
  clearWoundType,
  clearAllWounds,
  getTotalWounds,
  hasAnyWounds,
  getWoundCount,
  getNonZeroWoundTypes,
  isCriticallyWounded,
  getSkillPenalty,
  applyWoundPenaltyToSkill,
  getWoundSummary,
  type WoundDefinition,
  type WoundPenaltySummary,
  type EntityWithPenalties,
  type SkillCategory,
  type WoundSummary,
} from "./wound-tracker";

// Entity factory
export {
  createEntityFromCharacter,
  createEntityFromBestiary,
  createMonsterCounter,
  getNextMonsterNumber,
  createNumberedEntitiesFromBestiary,
  generateEntityId,
  cloneEntity,
  resetEntityForCombat,
  addResourceModifier,
  removeResourceModifier,
  tickResourceModifiers,
  type CharacterInput,
  type BestiaryEntryInput,
  type EntityCreationOptions,
  type MonsterCounter,
} from "./entity-factory";

// Turn management
export {
  sortInitiative,
  createInitiativeEntry,
  getInitiativeBonus,
  createTurnOrder,
  getCurrentTurnEntity,
  getNextTurnEntity,
  advanceTurn,
  removeFromTurnOrder,
  addToTurnOrder,
  updateInitiative,
  processTurnStart,
  processTurnEnd,
  processRoundStart,
  processRoundEnd,
  delayTurn,
  readyAction,
  isEntitysTurn,
  getRemainingActors,
  getActedEntities,
  isRoundComplete,
  getTurnPosition,
  type InitiativeRoll,
  type TurnOrderState,
  type TurnStartResult,
  type TurnEndResult,
  type RoundStartResult,
  type RoundEndResult,
} from "./turn-manager";

// Energy management
export {
  spendEnergy,
  spendAP,
  spendResources,
  restoreEnergy,
  restoreAP,
  restoreAPToMax,
  convertAPToEnergy,
  checkForDeathCheck,
  processEndureRoll,
  processFeatOfDefiance,
  hasEnoughEnergy,
  hasEnoughAP,
  canAfford,
  getEnergyPercent,
  getAPPercent,
  isFullEnergy,
  isFullAP,
  isCriticalEnergy,
  setEnergy,
  setAP,
  modifyMaxEnergy,
  modifyMaxAP,
  type SpendResult,
  type RestoreResult,
  type APConversionResult,
  type DeathCheckType,
  type EndureRollRequired,
  type FeatOfDefianceRequired,
  type DeathCheckRequired,
  type DeathCheckResult,
} from "./energy-manager";

// Hex grid system
export {
  CombatHex,
  createCombatGrid,
  createEmptyGrid,
  toHoneycombCoords,
  fromHex,
  hexDistance,
  axialDistance,
  getNeighbors,
  getNeighborInDirection,
  getHexRing,
  getHexesInRadius,
  getHexLine,
  getMovementRange,
  findPath,
  hasLineOfSight,
  getVisibleHexes,
  isInRange,
  getHexesInRange,
  getEntitiesInRange,
  moveEntity,
  placeEntity,
  removeEntity,
  findEntityPosition,
  setTerrain,
  getTerrain,
  gridToState,
  Direction,
  type MovementRangeOptions,
  type PathResult,
} from "./hex-grid";

// Channeling system
export {
  startChanneling,
  continueChanneling,
  releaseSpell,
  interruptChanneling,
  abortChanneling,
  isChanneling,
  getChannelingProgress,
  isReadyToRelease,
  getRemainingChannelingCost,
  getChannelingThresholds,
  estimateBlowback,
  calculateSpellCost,
  createSpellTemplate,
  getMinimumChannelingTurns,
  type StartChannelingResult,
  type ContinueChannelingResult,
  type ReleaseSpellResult,
  type InterruptResult,
  type AbortResult,
} from "./channeling-tracker";
